#!/usr/bin/env python3
"""Build wiki/search-index.js (window.__WIKI_INDEX__) for the offline wiki search.

One entry per <section id>, plus a page-level entry from the lead paragraph.
Stdlib only; run from the repo root or anywhere: `python3 wiki/build_search_index.py`.
"""
import html
import json
import os
import re

WIKI_DIR = os.path.dirname(os.path.abspath(__file__))

PAGES = [
    ("index.html", "Overview"),
    ("architecture.html", "Architecture"),
    ("self-improvement.html", "Self-Improvement"),
    ("internals.html", "Internals"),
    ("providers-auth.html", "Providers & Auth"),
    ("faq.html", "FAQ"),
]

TAG = re.compile(r"<[^>]+>")
WS = re.compile(r"\s+")


def strip_tags(s: str) -> str:
    return WS.sub(" ", html.unescape(TAG.sub(" ", s))).strip()


def build_entries(filename: str, nav_title: str):
    path = os.path.join(WIKI_DIR, filename)
    with open(path, encoding="utf-8") as fh:
        doc = fh.read()

    m = re.search(r"<main>(.*)</main>", doc, re.S)
    body = m.group(1) if m else doc
    # Drop content that isn't prose: mermaid diagram source and any scripts.
    body = re.sub(r'<pre class="mermaid">.*?</pre>', " ", body, flags=re.S)
    body = re.sub(r"<script.*?</script>", " ", body, flags=re.S)

    entries = []

    h1 = re.search(r'<h1[^>]*class="page-title"[^>]*>(.*?)</h1>', body, re.S)
    page_title = strip_tags(h1.group(1)) if h1 else nav_title
    lead = re.search(r'<p[^>]*class="lead"[^>]*>(.*?)</p>', body, re.S)
    if lead:
        entries.append({
            "u": filename, "p": nav_title, "t": page_title, "a": "",
            "x": strip_tags(lead.group(1))[:1400],
        })

    parts = re.split(r'(<section id="[^"]+">)', body)
    for i in range(1, len(parts), 2):
        sec_id = re.search(r'id="([^"]+)"', parts[i]).group(1)
        content = parts[i + 1] if i + 1 < len(parts) else ""
        heading = re.search(r"<h[23][^>]*>(.*?)</h[23]>", content, re.S)
        title = strip_tags(heading.group(1)) if heading else sec_id
        text = strip_tags(content)
        entries.append({
            "u": filename, "p": nav_title, "t": title, "a": sec_id,
            "x": text[:1400],
        })
    return entries


def main():
    index = []
    for filename, nav_title in PAGES:
        if os.path.exists(os.path.join(WIKI_DIR, filename)):
            index.extend(build_entries(filename, nav_title))
    payload = json.dumps(index, ensure_ascii=False, separators=(",", ":"))
    out = os.path.join(WIKI_DIR, "search-index.js")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("/* Generated by build_search_index.py — do not edit by hand. */\n")
        fh.write("window.__WIKI_INDEX__ = " + payload + ";\n")
    print(f"Wrote {out} — {len(index)} entries across {len(PAGES)} pages.")


if __name__ == "__main__":
    main()
